// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAEHs98Rm7nM8yzcBuYEO4EC7iv5jRHo',
    appId: '1:595481476226:web:dfb850bd2b4bdb004c889b',
    messagingSenderId: '595481476226',
    projectId: 'photoapp-c0241',
    authDomain: 'photoapp-c0241.firebaseapp.com',
    storageBucket: 'photoapp-c0241.firebasestorage.app',
    measurementId: 'G-YZEWQW5JHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2S5BOrIWEp85yrx_o5YW5xYK7uKFF-0',
    appId: '1:595481476226:android:dff7bbe4a9de705b4c889b',
    messagingSenderId: '595481476226',
    projectId: 'photoapp-c0241',
    storageBucket: 'photoapp-c0241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXx7by-KbCBLAtqPpd21K2TiJiZJq4P0g',
    appId: '1:595481476226:ios:c2b3e3466067b4ae4c889b',
    messagingSenderId: '595481476226',
    projectId: 'photoapp-c0241',
    storageBucket: 'photoapp-c0241.firebasestorage.app',
    iosBundleId: 'com.QuervQ.photoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXx7by-KbCBLAtqPpd21K2TiJiZJq4P0g',
    appId: '1:595481476226:ios:e7fe7f82b60006964c889b',
    messagingSenderId: '595481476226',
    projectId: 'photoapp-c0241',
    storageBucket: 'photoapp-c0241.firebasestorage.app',
    iosBundleId: 'com.example.photoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvAEHs98Rm7nM8yzcBuYEO4EC7iv5jRHo',
    appId: '1:595481476226:web:e1a928513af52b044c889b',
    messagingSenderId: '595481476226',
    projectId: 'photoapp-c0241',
    authDomain: 'photoapp-c0241.firebaseapp.com',
    storageBucket: 'photoapp-c0241.firebasestorage.app',
    measurementId: 'G-ZKF8TKJZ1N',
  );
}
